services:
  test_task_app:
    build: .
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}