version: '3.8'

services:
  test_task_app:
    image: chabur/test_task_app
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
      - db:/var/lib/postgresql/data 

volumes:
  db:
    driver: local
