definitions:
  model.AddBuilding:
    properties:
      city:
        type: string
      floors:
        type: integer
      name:
        type: string
      year:
        type: integer
    required:
    - city
    - name
    type: object
  model.Building:
    properties:
      city:
        type: string
      floors:
        type: integer
      id:
        type: integer
      name:
        type: string
      year:
        type: integer
    required:
    - city
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API server for working with buildings
  title: Building API
  version: "1.0"
paths:
  /api/v1/buildings:
    get:
      description: Get a list of buildings by filter
      operationId: get-buildings
      parameters:
      - description: City
        in: query
        name: city
        type: string
      - description: Year
        in: query
        name: year
        type: integer
      - description: number of floors
        in: query
        name: floors
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Building'
            type: array
        "400":
          description: Invalid request format
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: get buildings
      tags:
      - buildings
    post:
      consumes:
      - application/json
      description: Save the new building
      operationId: save-building
      parameters:
      - description: Building
        in: body
        name: building
        required: true
        schema:
          $ref: '#/definitions/model.AddBuilding'
      produces:
      - application/json
      responses:
        "200":
          description: ID of the saved building
          schema:
            type: integer
        "400":
          description: Invalid request format
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Save the building
      tags:
      - buildings
swagger: "2.0"
